### ISSUE TITLE
What is the dimension of the variable of "env"?

### ISSUE THREAD

**Issue by jinxcrazy** [Runjian-Chen/AdaM_MCL#1]
Hi, may I ask that what is the dimension of "env" in 
https://github.com/jinxcrazy/AdaM_MCL/blob/5b0a49eab679988b64b4153f6d71f43fc607f7d0/code/Data_processor/Bicocca_rc_dataset.py#L184

From https://github.com/Runjian-Chen/AdaM_MCL/blob/5b0a49eab679988b64b4153f6d71f43fc607f7d0/code/Data_processor/Bicocca_rc_dataset.py#L79
it is 3 dimension. It seems that when running Bicocca dataset in Data_processor, there will be some error. Maybe I did not set up it correctly. 

Could you help with this? thank you!

**Comment by Runjian-Chen** [comment]
Hello! Sorry for the late reply :(

The env_size will be automatically computed with the dxf file from the Bicocca dataset. Did you download that file?

Best,
Runjian
